### ISSUE TITLE
Use dashboard dark theme

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-console#1]

**Comment by PierreBesson** [comment]
I don't know if its possible to configure it without using the UI. If you know how to do it please submit a PR.
Also does the Timelion plugin works for you ? I had some issues earlier with it.

**Comment by cbornet** [comment]
Yes: set```"optionsJSON": "{\"darkTheme\":true}",``` in the dashboard json

**Comment by PierreBesson** [comment]
Never mind about the Timelion comment. It is now available in the Visualize panel as the "timeseries" option. That means we will have no issue to set up dashboards with it !

**Comment by PierreBesson** [comment]
I have added `darkTheme:true` to the existing dashboard. I also added the `kibana/load-localhost.sh` script to try out import of the dashboard JSON without rebuilding the image.

**Comment by cbornet** [comment]
I just found that there is also a
```
dashboard:defaultDarkTheme (Default: false)
New dashboards use dark theme by default
```
setting in the "Advanced settings" of Kibana that we can maybe switch to true.

**Comment by PierreBesson** [comment]
Sure. I will do it tomorrow.

Le ven. 11 mars 2016 18:29, Christophe Bornet <notifications@github.com> a
écrit :
