### ISSUE TITLE
Zipkin not showing any span and trace 

### ISSUE THREAD

**Issue by gitravik** [jhipster/jhipster-console#100]
Hello,
Zipkin is running fine but 
My **issue is I can't find any span or traces**. sometimes service name even not showing in the list.

I have clone latest jhipster-console and run it in my local machine.

>I have enable zipkin in my spring-boot service inside app-dev.yml file and also enable zipkin profile in pom.xml file like below 

# zipkin: 
        base-url: http://localhost:9411
        enabled: true
        locator:
            discovery:
                enabled: true

Here is my spring boot servile console log, I think zipkin is active   

 ----------------------------------------------------------

	Application 'demoapp1' is running! Access URLs:
	Local: 		http://localhost:8091
	Profile(s): 	[dev, zipkin, swagger]
----------------------------------------------------------

- I follow the link https://www.jhipster.tech/monitoring/#zipkin

- But still I cant see any span or traces in zipkin ui so can you please help me to figure it out.

**Comment by PierreBesson** [comment]
@gitravik Can you give me additional info. So this issue can be resolved more quickly.

**Comment by PierreBesson** [comment]
Closing as this no more info was provided.

**Comment by ivan86to** [comment]
Hello, i have the same issue, 

"Did you package your app with the "zipkin" maven profile ?" -> Yes 
SPRING_PROFILES_ACTIVE | prod,swagger,zipkin

Jhipster version 5.7.2

**Comment by PierreBesson** [comment]
@ivan86to Please don't comment on an old issue. If you have a bug please open another issue and provide the content or `jhipster info`

**Comment by st4rtx** [comment]
hi
any body find solution?

**Comment by st4rtx** [comment]
i find it
must write dependency in pom.xml file after log4j section :
                
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-zipkin</artifactId>
        </dependency>
