### ISSUE TITLE
Logstash Across Kubernetes Namespaces

### ISSUE THREAD

**Issue by somejavadev** [jhipster/jhipster-console#104]
Hi,
I am running the jhipster stack within kubernetes and have noticed that when deploying a microservice to another namespace (other than the one logstash is running in). Logstash does not receive any messages. Is there a way to configure the jhipster ELK stack to work across kubernetes namespaces? Ie have the ELK stack running in one namespace and allow any microservice independent of the namespace to log to it?

**Comment by PierreBesson** [comment]
Yes of course, you just need to set the correct logstash url that includes namespace info. As is explained in this k8s doc :  https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#namespaces-and-dns

So the URL should be something like :`jhipster-logstash.<namespace-name>.svc.cluster.local`

**Comment by somejavadev** [comment]
@PierreBesson, Thanks I have got it configured like this. I will see if I can add some additional logging to pin point the issue.
