### ISSUE TITLE
Install plugins?

### ISSUE THREAD

**Issue by WiteCastle** [jhipster/jhipster-console#116]
Is there a way to configure plugins from the docker-compose file using arguments or something? The only way I've figured out how to do it is to edit the Dockerfile.

I haven't worked with Docker extensively yet so I'm not even sure if it can be done. Is it possible to pass arguments to docker-compose that the Dockerfile could use to automatically install logstash plugins?

**Comment by PierreBesson** [comment]
Sorry for the late reply.
You either have to modify the Dockerfile present in this repo or create your own that would extend it like this :

```
FROM jhipster/jhipster-logstash
RUN install-plugin-command
```
