### ISSUE TITLE
Update dashboards for Micrometer

### ISSUE THREAD

**Issue by mraible** [jhipster/jhipster-console#118]
From JHipster Console's [documentation](https://www.jhipster.tech/monitoring/#jhipster-console):

> Note: As we switched from Dropwizard Metrics to Micrometer recently, the metrics dashboards are currently broken for applications generated with v5.8.0 and newer.

From @PierreBesson:

> I think people greatly overestimate the value of those dashboards because if you don't read them correctly you will misinterpret your data (you have to be careful because kibana will aggregate data and average percentile values from your timers if you have more than one instance of a given microservice. You will have to be extra careful when reading the result to know if they are meaningful..). So I would recommend Prometheus to study those metrics.

**Comment by jdubois** [comment]
I believe those dashboards are important to a number of people - at least @mraible and myself (there are chances I need them for an important keynote soon...) so I'm adding a $200 bug bounty here.

**Comment by PierreBesson** [comment]
It's done in master. Enjoy !

# http request timers
![Screenshot from 2019-07-19 18-52-42](https://user-images.githubusercontent.com/513471/61553452-c3301e80-aa5a-11e9-95ff-ab2d4073b3fb.png)
# graph any metrics
![Screenshot from 2019-07-19 18-45-24](https://user-images.githubusercontent.com/513471/61553454-c3301e80-aa5a-11e9-9cea-0805c53248da.png)
# jvm metrics
![Screenshot from 2019-07-19 18-41-41](https://user-images.githubusercontent.com/513471/61553455-c3c8b500-aa5a-11e9-8da5-18588509ffc9.png)
# cache (sorry no data to show)
![Screenshot from 2019-07-19 18-57-06](https://user-images.githubusercontent.com/513471/61553449-c3301e80-aa5a-11e9-8215-47050413dc42.png)

**Comment by PierreBesson** [comment]
I have claimed my bounty : https://opencollective.com/generator-jhipster/expenses/9163

**Comment by pascalgrimaud** [comment]
Just approuved, thanks @PierreBesson !

**Comment by mraible** [comment]
Will this be in the next JHipster release or is it a separate release cycle?

**Comment by PierreBesson** [comment]
We just need to update the version in generator-constants. I have already published the docker images
