### ISSUE TITLE
Fix publishing docker images to Docker Hub

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-console#119]
For the latest release, images where not published to docker hub.

Ping @pascalgrimaud

**Comment by pascalgrimaud** [comment]
Just done for v4.1.0
- https://cloud.docker.com/u/jhipster/repository/docker/jhipster/jhipster-console/tags
- https://cloud.docker.com/u/jhipster/repository/docker/jhipster/jhipster-elasticsearch/tags
- https://cloud.docker.com/u/jhipster/repository/docker/jhipster/jhipster-logstash/tags
- https://cloud.docker.com/u/jhipster/repository/docker/jhipster/jhipster-alerter/tags
- https://cloud.docker.com/u/jhipster/repository/docker/jhipster/jhipster-zipkin/tags
- https://cloud.docker.com/u/jhipster/repository/docker/jhipster/jhipster-import-dashboards/tags
- https://cloud.docker.com/u/jhipster/repository/docker/jhipster/jhipster-curator/tags
