### ISSUE TITLE
Graph ratios

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-console#13]
IMO it is better to graph ratios than raw values, esp. in the context of micro-services/multiple apps.
For intance I would like to graph JVM memory usage ratio = JVM memory used/ JVM memory max.
I couldn't do it with Kibana. With timelion I can do it with `.es(jvm.memory.total.used, avg:metric_value).divide(.es(jvm.memory.total.max, avg:metric_value))` but I didn't manage to split between instance_name like we do with Kibana.
Anyone has an idea ?

**Comment by PierreBesson** [comment]
After some research I didn't find a way to do exactly what you want. However I fount an alternative. I just finished to set up a nice dashboard for JVM metrics.

First I display the aggregated average for all apps.

![test1-jvm-aggregated](https://cloud.githubusercontent.com/assets/513471/13774720/c741abe2-eaa0-11e5-88eb-948c22d14273.png)

Noticed I added a number of logs for each app on the top left corner. You can click on one of those bars and it will restrict the data to this particular app.

![test1-jvm-1app](https://cloud.githubusercontent.com/assets/513471/13774871/9640570e-eaa1-11e5-8f09-78a864f82c89.png)

![test1-jvm-1gateway](https://cloud.githubusercontent.com/assets/513471/13774975/380ba926-eaa2-11e5-83a4-18a2e7b95e36.png)

@deepu105 Here you can use those graphs for your presentation ! William also added also you to a Google drive folder were we are going to put our performance test results.

**Comment by PierreBesson** [comment]
@cbornet too bad the timelion viz doesn't take into account that an app has been selected.

**Comment by cbornet** [comment]
Yes there is an [issue](https://github.com/elastic/kibana/issues/4584) opened on Kibana for agg pipelining and an [issue](https://github.com/elastic/timelion/issues/15) on timelion for term aggregation.
I also had a look at Grafana which has some support for ES pipeline aggs (moving average, derivative) but not yet between different timeseries.

Eventually, Graphite/Grafana has a lot more capacities for this kind of features (as it's a real TSDB). I looked at it as an alternative but in the case of a cluster of apps, I don't know how we can identify a node from another of the same app. Maybe with logstash pushing to graphite...

**Comment by PierreBesson** [comment]
@cbornet It works with Kibana v5 and the last version of Timelion. So much potential for metrics !

![cap](https://cloud.githubusercontent.com/assets/513471/19786253/49eb8cb2-9c9d-11e6-9b5f-6781393fbdc9.png)

Look at the tiny red line on the right...

**Comment by PierreBesson** [comment]
Implemented in https://github.com/jhipster/jhipster-console/commit/33d54082f396a151b9e3ba984f221f833f66a1a3
<img width="1380" alt="ratio" src="https://cloud.githubusercontent.com/assets/513471/19888609/fadde9f8-a02f-11e6-9e50-3ffb4386276e.png">
