### ISSUE TITLE
Cannot launch JHipster Console in Windows

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-console#14]
I have this error for the JHipster-Console container when launching 'docker-compose up' on Windows.

```
/docker-entrypoint.sh: /tmp/entrypoint.sh: /bin/bash^M: bad interpreter: No such file or directory
/docker-entrypoint.sh: line 25: /tmp/entrypoint.sh: Success
/docker-entrypoint.sh: /tmp/entrypoint.sh: /bin/bash^M: bad interpreter: No such file or directory
/docker-entrypoint.sh: line 25: /tmp/entrypoint.sh: Success
/docker-entrypoint.sh: /tmp/entrypoint.sh: /bin/bash^M: bad interpreter: No such file or directory
/docker-entrypoint.sh: line 25: /tmp/entrypoint.sh: Success
```
@pascalgrimaud I need your help here.

**Comment by pascalgrimaud** [comment]
@PierreBesson : I will play Docker on Windows, during this WE
I will have a look on it

**Comment by pascalgrimaud** [comment]
1st quick answer : https://github.com/jhipster/jhipster-console/blob/master/kibana/entrypoint.sh#L1
You have to find the base image of kibana:4.4.1
maybe no `bash` is installed, maybe it's `sh` instead

**Comment by pascalgrimaud** [comment]
In fact, bash and sh are correctly installed. The problem comes from Windows, when copying file during docker build.
It's nice to know it, because I never build image on Windows before today :-)

**Comment by PierreBesson** [comment]
@pascalgrimaud Thanks a lot ! I would have never found a fix for this issue.
