### ISSUE TITLE
Volumes for Windows and Mac OS can be mounted only on User directory

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-console#17]
Raised by @pascalgrimaud, in https://github.com/jhipster/generator-jhipster/issues/3221#issuecomment-198862523
Solutions:
1)
* Add instructions to the README
* Add commented out lines for windows and mac os (using a sample /User path that they must correct)
* Complete documentation

**Comment by PierreBesson** [comment]
Relevant information as been added to the docs: https://github.com/jhipster/jhipster.github.io/pull/231.

**Comment by deepu105** [comment]
@PierreBesson can you also add the commented out lines that can be used on the elk.yml file you mentioned above?
