### ISSUE TITLE
Merge JHipster-Console and Elastalert Containers

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-console#18]
I have been evaluating Elastalert as an alerting solution and it is working really well. I have made an alerting dashboard for Kibana that display recent alerts.

![alerting-dashboard](https://cloud.githubusercontent.com/assets/513471/13914536/436b3050-ef4f-11e5-939a-2bf44c1f2545.png)

So now I want to include it in the main image so that users don't have to deal with two different containers.

**Comment by deepu105** [comment]
Nice +1

Thanks & Regards,
Deepu

**Comment by PierreBesson** [comment]
Fixed in b6512f7058304df827ece2b90c72a33eadafcd76.
