### ISSUE TITLE
Index patterns fields are not always getting created by Kibana

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-console#19]
It causes dashboards to display errors when displayed started.

This can be solved in some cases by refreshing the index pattern so I added a tip to the docs but it is not enough in all cases.

Should we configure logstash differently to solve this problem ?

**Comment by cbornet** [comment]
I think we could preload most of the indexes that will be used since we know them in advance (like the metric_* ones for instance).

**Comment by PierreBesson** [comment]
What should be done is creating an index template for the logstash-* index.

https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html

**Comment by PierreBesson** [comment]
Current status is we preload the Kibana index in Elastic with the script but it seems the user has to click "create" at least once anyway.
