### ISSUE TITLE
Migrate the JHipster Console to Kibana 5

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-console#24]
https://www.elastic.co/blog/kibana-5-0-0-alpha1?blade=tw

Looks very cool, too bad there doesn't seem to be docker images available.

**Comment by deepu105** [comment]
It indeed looks super awesome. I love the design. But should we wait for a
stable RC?

Thanks & Regards,
Deepu

**Comment by PierreBesson** [comment]
Yes indeed, but looking at the pace elastic release their product, it should be released shortly.
Also it seems to have better features for monitoring, as well as way to integrate your own plugins.

My idea, was that in the future we could develop a JHipster plugin to show a the registry screen +  something like spring boot admin: https://github.com/codecentric/spring-boot-admin
Maybe we can even integrate things like Hystrix Dashboard and Zipkin http://zipkin.io/

**Comment by jhulick** [comment]
+1 FWIW, there is a nice registry dashboard with downstream services config and hystrix aggregator (via turbine), like the spring boot admin dashboard here: https://github.com/VanRoy/spring-cloud-dashboard

**Comment by PierreBesson** [comment]
Those projects are nice but one concern I have, is that I'm not sure if they have been given the authorization by the Spring Team to use the names "spring boot" and "spring cloud".

**Comment by PierreBesson** [comment]
I finally managed to have the ELK v5 stack working ! I commited my work on the [elastic-v5 branch](https://github.com/jhipster/jhipster-console/tree/elastic-v5).

Warning, all dashboards are broken !

**Comment by cbornet** [comment]
FYI we now have cassandra cluster metrics if you want

**Comment by PierreBesson** [comment]
@cbornet. Oh yeah, @jdubois told me today about it. I will try to do something in the coming weeks...

**Comment by PierreBesson** [comment]
Work on the elastic v5 migration has been commited to master. It works fine but the dashboards will need to be done again.

The logo also needs to be redone because of Kibana's redesign, now it looks like this:
![capture du 2016-10-27 23-34-22](https://cloud.githubusercontent.com/assets/513471/19786454/57a0ac9c-9c9e-11e6-9651-e52067c13a3c.png)
And in collapsed mode:
![capture du 2016-10-27 23-35-36](https://cloud.githubusercontent.com/assets/513471/19786488/77c5a98c-9c9e-11e6-855f-9a6505710b0b.png)

Actually the [original Kibana logo is this one](https://github.com/elastic/kibana/blob/01b426c94957adc7914371d91c9989b3a155a526/src/ui/public/images/kibana.svg) all white and transparent to go with the ping background.

**Comment by deepu105** [comment]
We can make it transparent as well. Ill try to do it this weekend

Thanks & regards,
Deepu

**Comment by PierreBesson** [comment]
Dashboard migration has been done here: https://github.com/jhipster/jhipster-console/commit/33d54082f396a151b9e3ba984f221f833f66a1a3
I will soon release a v2 of the Console.

**Comment by romaindequidt** [comment]
@PierreBesson May you list me the remaining tasks before releasing V2?

**Comment by PierreBesson** [comment]
Yes everything works except for alerting, you can start using it by moving to the v2.0.0-beta docker tag : https://github.com/jhipster/jhipster-console/releases/tag/v2.0.0-beta
I'm just waiting for elastalert to release a new version compatible with the elastic stack v5.

**Comment by romaindequidt** [comment]
@PierreBesson my .yo-rc.json looks like this:
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.0",
    ...
    "searchEngine": "elasticsearch",
    ...
  }
}
```
I choose the microservices architecture (gateway, microservice, registry, console...) and try to start it into production environnement.

The spring.data.elasticserach settings use the elasticsearch from console as the "cluster-nodes".
Unfortunatelly the ES client (2.4) is not fully compatible with ES node (5.X).

The following warning is raised again and again:

> [unmapped_type:string] should be replaced with [unmapped_type:keyword]

And this dependency doesn't seem to be availalabe form ES 5.X:
```
<dependency>
     <groupId>org.springframework.boot</groupId>
     <artifactId>spring-boot-starter-data-elasticsearch</artifactId>
</dependency>
```

Just FYI
