### ISSUE TITLE
Correct automatic build tagging on docker-hub

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-console#25]
I just realized that tags for automatic builds at docker hub is completely broken. It is actually rebuilding the latest master with 1.0.0 tag.
@pascalgrimaud, if you have access can you correct this.

**Comment by pascalgrimaud** [comment]
I try to have a look this afternoon
Le 13 avr. 2016 10:19 AM, "Pierre Besson" <notifications@github.com> a
écrit :

**Comment by PierreBesson** [comment]
Thanks a lot !

**Comment by pascalgrimaud** [comment]
I did the same like jhipster-registry. It should be resolved by this :
> On Docker Hub, in build settings, I delete the type: tag + v1.0.0
So the tag v1.0.0 on docker hub won't be updated every commit/push
Don't worry, the tag v1.0.0 still exists => https://hub.docker.com/r/jhipster/jhipster-console/tags/

But there is still an issue : https://github.com/jhipster/jhipster-registry/issues/35

**Comment by PierreBesson** [comment]
I will check today with @jdubois that all project have correct automated build.

**Comment by pascalgrimaud** [comment]
Cool! I hope it will work!
The automated build in Docker Hub should be correct.
The main issue is with github => we need to delete webhooks and need to update service with Docker. See my post https://github.com/jhipster/jhipster-registry/issues/35#issuecomment-203626119

**Comment by PierreBesson** [comment]
This is finally corrected !

**Comment by pascalgrimaud** [comment]
@PierreBesson : I hope ! I've just checked the generator-jhipster project and there is:
- a commit from Deepu on master branch, 3 hours ago

And on Docker hub:
- jhipster/jhipster:master : 3 hours ago
- jhipster/jhipster:latest : 18 hours ago
- jhipster/jhipster:v3.1.0 : 18 hours ago

So I think it's finally OK !!! Thanks to Julien
