### ISSUE TITLE
No log for the logstash-* pattern

### ISSUE THREAD

**Issue by nodje** [jhipster/jhipster-console#27]
Starting the console with the default config, I can access the Kibana dashboard but it doesn't seem to find anything under the `logstash-*` pattern.

I've verified that jhipster-cloud is sending the log through the appender to the console IP on UDP port 5000. (tcpdump on the sending machine)
And I can see that that the docker machine has started the logstash instance and is listening to UDP 5000 (with `netstat`)

Is there anything I should do to get the default config working?

When I go to Kibana's settings tab I have this message `Unable to fetch mapping. Do you have indices matching the pattern?`

And on the Discover tab here's what I have if it can help:
![screen shot 2016-04-21 at 18 32 40](https://cloud.githubusercontent.com/assets/75604/14706133/7fb52c6a-07ef-11e6-9432-3d231351ee71.png)

On the log side, I get a corresponding 404:
`jhipster-console_1   | {"type":"response","@timestamp":"2016-04-21T10:30:53+00:00","tags":[],"pid":1,"method":"get","statusCode":404,"req":{"url":"/elasticsearch/logstash-*/_mapping/field/*?_=1461234653807&ignore_unavailable=false&allow_no_indices=false&include_defaults=true","method":"get","headers":{"host":"192.168.0.74:5601","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0","accept":"application/json, text/plain, */*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","referer":"http://192.168.0.74:5601/app/kibana","kbn-version":"4.5.0","connection":"keep-alive"},"remoteAddress":"10.0.2.2","userAgent":"10.0.2.2","referer":"http://192.168.0.74:5601/app/kibana"},"res":{"statusCode":404,"responseTime":7,"contentLength":9},"message":"GET /elasticsearch/logstash-*/_mapping/field/*?_=1461234653807&ignore_unavailable=false&allow_no_indices=false&include_defaults=true 404 7ms - 9.0B"}`

**Comment by PierreBesson** [comment]
Hi @nodje, 
Do see anything in the logstash container logs (`docker-compose logs elk-logstash`) ?

I have seen this problem before, it can be solved by recreating the index. First make sure that logstash has received some logs then go to settings > index pattern and create a new index pattern here.

If it still doesn't work, try recreating the elk-elasticsearch containers `docker-compose stop elk-elasticsearch` then `docker-compose rm elk-elasticsearch` then `docker-compose up elk-elasticsearch`.

**Comment by nodje** [comment]
Thanks for your support @PierreBesson, I got it working, I was obviously not receiving logs from logstash yesterday even though hipstercloud was sending them. Probably a port mapping issue from OsX Host to Docker guest...
I can see them clearly in the logs now as I run docker-compose without daemonizing it.

Just a question about something I can't quite make out: what does the pattern `logstash-*` matches in the logs? I can't see anything in the logs having the `logstash` pattern. I mean `*` gets everything of course but how can `logstash-*` limits the index to the logstash entry only?

**Comment by PierreBesson** [comment]
@nodje `logstash-*` refers to the elasticsearch index that logstash will write to (see in the [docs](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-index). Currently the console creates automatically 2 indexes [master/jhipster-console/dashboards/index-pattern](https://github.com/jhipster/jhipster-console/tree/master/jhipster-console/dashboards/index-pattern): `logstash-*` for logs and `elastalert-status` for alerts.

Anyway it might be interesting to add a troubleshooting section to the jhipster console docs.
