### ISSUE TITLE
Deploying jhipster-console to different remote docker machines

### ISSUE THREAD

**Issue by NOTtardy** [jhipster/jhipster-console#31]
Hi all

I have some questions about deploying jhipster-console to different remote docker machines. If you could have a look at [my question on stackoverflow](http://stackoverflow.com/questions/36874749/deploying-jhipster-console-to-different-remote-docker-machines) and give your feedback, that would be awesome.

Thanks!

**Comment by jdubois** [comment]
I'm closing this as per our guidelines, as this is a cross-post with StackOverflow

**Comment by NOTtardy** [comment]
Sorry

**Comment by jdubois** [comment]
No problem! I'm just trying to keep the issues clean.
