### ISSUE TITLE
jhipster-console cannot resolve links on Docker Cloud

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/jhipster-console#35]
@PierreBesson same issue that makes us change the Dockerfile to use the latest version from alpine. But researching jhipster-console, it uses kibana, and kibana uses directly debian. 

Any ideas why jhipster-console container is not able to resolve the hostnames on Docker Cloud Stack configuration?

**Comment by marcelinobadin** [comment]
No, the problem was on my configuration. There is no issue here.

**Comment by PierreBesson** [comment]
OK, no problem.
