### ISSUE TITLE
Simplify distribution by creating jhipster-logstash, jhipster-elasticsearch and jhipster-alerting official images

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-console#36]
Create the following automated build at docker hub in the JHipster organisation:
- jhipster-elasticsearch (simple wrapper over a specific version of the official image)
- jhipster-logstash (same but with a logstash.conf file already included so it can be deployed easily see #34 )
- jhipster-alerting or jhipster-console-alerting or jhipster-elastalert

I would like to introduce this change as a way to simplify development and maintenance of the console. People won't have to know which version of logstash, elasticsearch to use with the console, they can just use the same version for everything.

Basically, we would need to wrap all official images in our own, I can find many reasons why this would be good :
- Only one version to know to install the stack, so this will simplify the docs.
- You can omit the version number and it will latest and it will work (this is not possible currently)
- It would be easier to keep track of which versions of those images works well together (if wanting to use older versions).
- (optional) We will be able to move to alpine even before the official images. This is not so hard to do (see [kost/docker-alpine/blob/master/alpine-elk/Dockerfile](https://github.com/kost/docker-alpine/blob/master/alpine-elk/Dockerfile))
- It would be easier for people to customize the console after doing a git clone. So it would be easier for them to contribute.

The drawbacks:
- We multiply the number of images
- our images are not "official" anymore (not really a problem as we are open source and you can just fork us)

**Comment by pascalgrimaud** [comment]
The most important thing is to use official base image => the `FROM` in our Dockerfile must be followed by an official image

**Comment by PierreBesson** [comment]
I have done the refactoring in master.
The following images needs to be created with the same tag parameters as the `jhipster-console` image:
- `jhipster/jhipster-elasticsearch`

Dockerfile location: `/jhipster-elasticsearch`
- `jhipster/jhipster-logstash`

Dockerfile location: `/jhipster-logstash`
- `jhipster/jhipster-alerter`

Dockerfile location: `/jhipster-alerter`

**Comment by jdubois** [comment]
@PierreBesson I created the 3 repos and triggered a first build on each, it should be OK!

**Comment by PierreBesson** [comment]
@jdubois It works fine ! Now I just need to rename things like `elk-elasticsearch` to `jhipster-elasticsearch` and it should be complete.
