### ISSUE TITLE
Alerts Count visualization problem

### ISSUE THREAD

**Issue by szmizorsz** [jhipster/jhipster-console#37]
Hi,
I am experimenting with your console and alterer, good stuff, but I think I found a problem:

On alerting dashboard the Alerts Count visualization does not work:
"A field associated with this object no longer exists in the index pattern."

It seems to be the match_body.app_name which is used in a terms aggregation.
But if I check the elastalert_status mapping in ES for match_body:
"match_body": {
            "type": "object",
            "enabled": false
          }

From ES documentation:
"The enabled flag allows to disable parsing and indexing a named object completely. This is handy when a portion of the JSON document contains arbitrary JSON which should not be indexed, nor added to the mapping."

Meaning that building aggregations on match_body does not work unless you recreate the elastalert_status index and change the enable flag. But I am not sure if it is a good idea because match_body contains the whole original document that matched including the message field that can contain any arbitrary text like exceptions without any limitation. So it could blow the index.

Please, correct me if I misinterpret anything.
Thanks,
Szabolcs

**Comment by PierreBesson** [comment]
Hi,
What version of the console are you using ? Have you developped custom alerts for your use case.

Actually the alerting dashboards will only works  if you have configured Elastalert. Otherwise it is completely useless and you can remove it. 

The way alerting is configured is changing a lot with the latest version (now it has it's own image called jhipster-alerter). Also I have not seen so much interest in it for now, so it's not a priority for me to improve it.

**Comment by szmizorsz** [comment]
Hi Pierre,
I forked the 1.2.0 version and started using without Docker images. I manually set up everything and used your load scripts. But regarding this problem I do not think this makes difference.

Yes, I configured Elastalert and played with the log_error rule that is shipped with the Jhipster-alerter. 
When I noticed that the Alerts Count visualization object on the Alerting dashboard does not work because of using aggregations on an object (match_body) which does not support that (not indexed).

I understand that these are just examples so you do not have much interest to maintain them. Just wanted to let you know that I think this vizualization object is not a working example.

**Comment by PierreBesson** [comment]
So the Elastalert alerting dashboard has been removed in recent versions. So I'm closing this issue, hopefully we can get it back in a future version or move to an alternative alerting solution.
