### ISSUE TITLE
Using environment instead of hard-coded

### ISSUE THREAD

**Issue by ghahramani** [jhipster/jhipster-console#38]
Hi,
I have problem with jhipster-console in network_mode: host

Please use Environment Variables instead of jhipster-elasticsearch in line:
https://github.com/jhipster/jhipster-console/blob/master/jhipster-console/entrypoint.sh#L8

**Comment by PierreBesson** [comment]
You have a good point. It is done it in other places but I kind of rushed things when I did the refactor with jhipster-logstash and jhipster-elasticsearch.

Would you consider making a PR to fix this ? Otherwise please wait a little and I will fix this in the coming days.

**Comment by ghahramani** [comment]
these days I'm so busy but I will make PR ASAS

**Comment by PierreBesson** [comment]
@ghahramani I just fixed it. Sorry for the wait.
This was actually very important as jhipster-console's didn't allow to change the ES URL until now.
Some improvements will be needed in the future, like being able to provide ES login/password by environment vars or use https.
