### ISSUE TITLE
Allow configuration of jhipster-alerter by env vars

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-console#39]
Add the following env vars:
- es_host
- es_port
- run_every
- buffer_time

**Comment by cdaller** [comment]
another elastalert github project that solved this problem: https://github.com/fiunchinho/docker-elastalert/blob/master/docker-entrypoint.sh

**Comment by PierreBesson** [comment]
@cdaller Looks like this is done by someone more experienced than me. This is really nice code ! @fiunchinho, I hope you don't mind if I take some inspiration from you in the future.

**Comment by fiunchinho** [comment]
np! Just glad I could help :)
