### ISSUE TITLE
Not forwarding logs after a while

### ISSUE THREAD

**Issue by ghahramani** [jhipster/jhipster-console#41]
Hi, I encountered to a wired issue.

After all the microservices are up I can see the logs very well in dashboard, all metrics logs and application logs.

But after one day or less, I cannot see the metrics/application logs of some microservices, the interested part is gateway always is there, I never saw it happened for gateway, it will happen only for microservices. 

Note: I can see all the logs in file logs and container logs but dashboard

**Comment by PierreBesson** [comment]
This must be a problem with 
https://github.com/logstash/logstash-logback-encoder
Please look through their issues maybe you will recognise yours. Also you can try updating the dependency version to see if it fixes your problem. I don't know If the version included in JHipster is the last version of logstash-encoder. If it is not this should be fixed.

**Comment by ghahramani** [comment]
@PierreBesson I didn't touch anything from jhipster default, it's like that you released, just I uncomment the AsyncAppender that you put comment there for production. Are you getting this behavior with your version? My jhipster version is 3.0 but my jhipster-console and elk stuff is v1.3.0 in docker-compose configuration. Should I look at another place except that you sent or check something in my code?

**Comment by ygokirmak** [comment]
@PierreBesson we realized that some of our microservices "restarts" after 1-2 minutes and after second start they don't send any log to logstash.. 

in first start we see below log
```
2016-07-27 08:54:29,616 DEBUG [background-preinit] logging: Logging Provider: org.jboss.logging.Slf4jLoggerProvider found via system property
```
bug after the second one logging provider log is missing..

```
2016-07-27 08:54:25,386 INFO  [restartedMain] DemoApp: Starting DemoApp on 7adf92b8bc96 with PID 85 (/home/infoowl/project/target/classes started by infoowl in /home/infoowl/project)
2016-07-27 08:54:25,471 DEBUG [restartedMain] DemoApp: Running with Spring Boot v1.3.5.RELEASE, Spring v4.2.6.RELEASE
2016-07-27 08:54:25,487 INFO  [restartedMain] DemoApp: The following profiles are active: dev
2016-07-27 08:54:29,616 DEBUG [background-preinit] logging: Logging Provider: org.jboss.logging.Slf4jLoggerProvider found via system property
2016-07-27 08:54:32,436 INFO  [restartedMain] DemoApp: Started DemoApp in 9.865 seconds (JVM running for 14.572)
2016-07-27 08:54:45,937 DEBUG [restartedMain] HttpURLConnection: sun.net.www.MessageHeader@3959b7066 pairs: {GET /config/transformation/dev/master HTTP/1.1: null}{Accept: application/json, application/*+json}{Authorization: Basic YWRtaW46YWRtaW4=}{User-Agent: Java/1.8.0_91}{Host: registry:8761}{Connection: keep-alive}
2016-07-27 08:54:46,512 DEBUG [restartedMain] HttpURLConnection: sun.net.www.MessageHeader@12bba63311 pairs: {null: HTTP/1.1 200 OK}{Server: Apache-Coyote/1.1}{X-Content-Type-Options: nosniff}{X-XSS-Protection: 1; mode=block}{Cache-Control: no-cache, no-store, max-age=0, must-revalidate}{Pragma: no-cache}{Expires: 0}{X-Application-Context: jhipster-registry:dev,native:8761}{Content-Type: application/json;charset=UTF-8}{Transfer-Encoding: chunked}{Date: Wed, 27 Jul 2016 08:54:46 GMT}
2016-07-27 08:54:46,777 INFO  [restartedMain] DemoApp: The following profiles are active: dev
2016-07-27 08:55:01,347 WARN  [restartedMain] ConfigurationClassPostProcessor: Cannot enhance @Configuration bean definition 'refreshScope' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.
2016-07-27 08:55:03,767 DEBUG [restartedMain] AsyncConfiguration: Creating Async Task Executor
2016-07-27 08:55:07,072 DEBUG [restartedMain] MetricsConfiguration: Registering JVM gauges
2016-07-27 08:55:07,169 DEBUG [restartedMain] MetricsConfiguration: Initializing Metrics JMX reporting
2016-07-27 08:55:07,281 INFO  [restartedMain] MetricsConfiguration: Initializing Metrics Log reporting
2016-07-27 08:55:16,352 INFO  [localhost-startStop-1] WebConfigurer: Web application configuration, using profiles: [dev]
2016-07-27 08:55:16,359 DEBUG [localhost-startStop-1] WebConfigurer: Initializing Metrics registries
2016-07-27 08:55:16,383 DEBUG [localhost-startStop-1] WebConfigurer: Registering Metrics Filter
2016-07-27 08:55:16,400 DEBUG [localhost-startStop-1] WebConfigurer: Registering Metrics Servlet
2016-07-27 08:55:16,402 INFO  [localhost-startStop-1] WebConfigurer: Web application fully configured
2016-07-27 08:55:19,343 INFO  [localhost-startStop-1] CoreApp: Running with Spring profile(s) : [dev]
2016-07-27 08:55:24,670 INFO  [restartedMain] LoggingConfiguration: Initializing Logstash logging
2016-07-27 08:55:24,781 INFO  [restartedMain] LoggingConfiguration: Logstash customFields: '{"app_name":"transformation","app_port":"9093","instance_id":"transformation:4afb19b3a2763ed887b8d69d246082e6"}', config: 'net.infoowl.hepsiburada.core.config.JHipsterProperties$Logging$Logstash@96d9ebe[enabled=true,host=elk-logstash,port=5000,queueSize=512]'
2016-07-27 08:55:35,367 DEBUG [restartedMain] CacheConfiguration: No cache
2016-07-27 08:55:40,071 DEBUG [restartedMain] DatabaseConfiguration: Configuring Mongeez
2016-07-27 08:55:40,245 INFO  [restartedMain] FilesetXMLReader: Parsing XML Fileset file master.xml
2016-07-27 08:55:40,275 INFO  [restartedMain] FilesetXMLReader: Num of changefiles found 0
2016-07-27 08:55:41,089 DEBUG [restartedMain] SwaggerConfiguration: Starting Swagger
2016-07-27 08:55:41,218 DEBUG [restartedMain] SwaggerConfiguration: Started Swagger in 118 ms
2016-07-27 08:55:55,610 WARN  [restartedMain] URLConfigurationSource: No URLs will be polled as dynamic configuration sources.
2016-07-27 08:55:56,975 WARN  [restartedMain] URLConfigurationSource: No URLs will be polled as dynamic configuration sources.
2016-07-27 08:56:00,036 DEBUG [cron4j::scheduler[20b6349f63f32eea2d00877b000001562b91269c7714a479]::launcher[20b6349f63f32eea238ca33a000001562b9155042b804084]] CronPlugin: Found crontab config url org.crsh.vfs.Resource@7a65b25c
2016-07-27 08:56:00,788 INFO  [restartedMain] DemoApp: Starting DemoApp on 7adf92b8bc96 with PID 85 (/home/infoowl/project/target/classes started by infoowl in /home/infoowl/project)
2016-07-27 08:56:00,788 DEBUG [restartedMain] DemoApp: Running with Spring Boot v1.3.5.RELEASE, Spring v4.2.6.RELEASE
2016-07-27 08:56:00,788 INFO  [restartedMain] DemoApp: The following profiles are active: dev
2016-07-27 08:56:01,290 INFO  [restartedMain] DemoApp: Started DemoApp in 0.899 seconds (JVM running for 103.426)

```

another observation.. see second start is just "0.899 seconds" which is not possible.. Actually it seems second one is not a real start but logstash connection is gone..

**Comment by PierreBesson** [comment]
Did you guys tried to update the logstash-encoder version to see if it fixes the problem. Anyway, this is probably a problem with:
https://github.com/logstash/logstash-logback-encoder
As I'm in vacation right now I can't investigate the issue myself.

**Comment by ygokirmak** [comment]
yes.. upgraded to https://mvnrepository.com/artifact/net.logstash.logback/logstash-logback-encoder/4.7

**Comment by ygokirmak** [comment]
@PierreBesson  latest observation.. when we remove @EnableBinding(x.class) from application,
second restart disappears and logs are send to logstash successfully

**Comment by ygokirmak** [comment]
@PierreBesson  we found the problem and discussion is here

https://github.com/spring-projects/spring-boot/issues/6688

we have also a workaround for jhipster;

changing LoggingConfiguration to 

```
@Configuration
public class LoggingConfiguration implements ApplicationListener<ContextRefreshedEvent> {

    private final Logger log = LoggerFactory.getLogger(LoggingConfiguration.class);

    private JHipsterProperties properties;
    private LogstashConfigurator logstashConfigurator;

    @Inject
    public void setLogstashConfigurator(LogstashConfigurator logstashConfigurator) {
        this.logstashConfigurator = logstashConfigurator;
    }

    @Inject
    public void setProperties(JHipsterProperties properties) {
        this.properties = properties;
    }

    @Override
    public void onApplicationEvent(ContextRefreshedEvent event) {
        if (properties.getLogging().getLogstash().isEnabled()) {
            logstashConfigurator.addLogstashAppender();
            log.info("Added Logstash Appender");
        }
    }
}

```

**Comment by PierreBesson** [comment]
Wow, it's impressive that you've found the root of the problem and not given up after all those days !

Reading your issues on spring-boot and spring-cloud-stream github I realize that setting the logstash appender logback configuration programmatically (not with logback.XML) is having consequences that I couldn't imagine...

Cc @jdubois, @gmarziou, I don't know enough about Logback to know if it would be sensible to add @ygokirmark's workaround in JHipster. Can I have your inputs ?
As far as we know the problem happens only when using spring cloud stream but we can't be sure...

**Comment by gmarziou** [comment]
Looks good to me and maybe it could be also a solution for the problem I have started to discuss on [our mailing list](https://groups.google.com/forum/#!topic/jhipster-dev/TJFctx0fjeQ).

Great work @ygokirmak

**Comment by ygokirmak** [comment]
Setting configuration via logback.xml not programmatic is also a solution
but in that case I can not get app_name and instance id from spring configuration bec it is created after logback.xml I think...

**Comment by gmarziou** [comment]
Your code works well for the initial configuration.

However it does help for my use case, which is to change log level in logback.xml which results in a stop and start on logging context.  On stop event, the logstash appender is closed and on start it is not re-created.

I have looked at event listeners but I found the doc a bit difficult. I'm looking at declaring the appender in xml fully or partially.

**Comment by gmarziou** [comment]
I defined the logstash appender in logback-spring.xml and got it working on reset when I use hard-coded values:

~~~xml
<configuration scan="true" scanPeriod="5 seconds" debug="true">

    <include resource="org/springframework/boot/logging/logback/base.xml" />

            <appender name="LOGSTASH" class="net.logstash.logback.appender.LogstashSocketAppender">
               <host>my-elk-host</host>
               <port>5000</port>
               <customFields>{"app_name": "gateway", "app_port": "8087","instance_id": "1234"}</customFields>
            </appender>

            <root level="DEBUG">
                <appender-ref ref="CONSOLE" />
                <appender-ref ref="LOGSTASH" />
            </root>

</configuration>
~~~

I tried to use Janino to put some conditionals but it seems it fails to read app properties:.

~~~xml
   <if condition='property("jhipster.logging.logstash.enabled").contains("true")'>
~~~

**Comment by ygokirmak** [comment]
@gmarziou my workaround is working for us.. can you share your LoggingConfiguration. 

and as I said pure logback.xml solution is not working bec it is not possible to access application properties in logback.xml

**Comment by gmarziou** [comment]
My LoggingConfiguration is the default one generated by JHipster or yours.

I set debug attribute to true in the lobgack configuration and took a trace, it show clearly that on a reset event the logstash appender is stopped but not restarted while the console appender is.

<details>
  <summary>Log when changing log level while app is running</summary>
17:07:18,048 |-INFO in ReconfigureOnChangeTask(born:1471878398044) - Detected change in configuration files.
17:07:18,048 |-INFO in ReconfigureOnChangeTask(born:1471878398044) - Will reset and reconfigure context named [default]
17:07:18,049 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_LOGSTASH] - Worker thread will flush remaining events before exiting.
17:07:18,050 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_LOGSTASH] - Queue flush finished successfully within timeout.
17:07:18,048 |-INFO in ReconfigureOnChangeTask(born:1471878398044) - Detected change in configuration files.
17:07:18,048 |-INFO in ReconfigureOnChangeTask(born:1471878398044) - Will reset and reconfigure context named [default]
17:07:18,049 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_LOGSTASH] - Worker thread will flush remaining events before exiting.
17:07:18,050 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_LOGSTASH] - Queue flush finished successfully within timeout.
17:07:18,055 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [file:c:/projets/ecobil/logback.xml]
17:07:18,055 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 5 seconds
17:07:18,057 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
17:07:18,057 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
17:07:18,057 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
17:07:18,058 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.central.gateway] to WARN
...
17:07:18,062 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [sun.rmi.transport] to WARN
17:07:18,062 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Adding LoggerContextListener of type [ch.qos.logback.classic.jul.LevelChangePropagator] to the object stack
17:07:18,063 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@16a4804 - Setting level of jul logger [com.codahale.metrics] to null
...
17:07:18,064 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@16a4804 - Setting level of jul logger [org.apache.catalina.startup.DigesterFactory] to null
17:07:18,070 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@16a4804 - Propagating DEBUG level on Logger[ROOT] onto the JUL framework
17:07:18,070 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@16a4804 - Propagating WARN level on Logger[ch.qos.logback] onto the JUL framework
...
17:07:18,072 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@16a4804 - Propagating WARN level on Logger[sun.rmi.transport] onto the JUL framework
17:07:18,072 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Starting LoggerContextListener
17:07:18,072 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
17:07:18,072 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@16a4804 - Propagating WARN level on Logger[ROOT] onto the JUL framework
17:07:18,072 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to Logger[ROOT]
17:07:18,072 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
17:07:18,073 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@155dab1 - Registering current configuration as safe fallback point
</details

**Comment by ygokirmak** [comment]
@gmarziou we changed default LoggingConfiguration and add implement application listener

```
public class LoggingConfiguration implements ApplicationListener<ContextRefreshedEvent> {
```

and we are adding logstash appender on context refreshed event.. now it works as expected

```
    @Override
    public void onApplicationEvent(ContextRefreshedEvent event) {
        if (properties.getLogging().getLogstash().isEnabled()) {
            logstashConfigurator.addLogstashAppender();
            log.info("Added Logstash Appender");
        }
    }
```

**Comment by gmarziou** [comment]
I already had this and it does not work for me because I don't get a ContextRefreshedEvent event. I put a breakpoint in `LoggingConfiguration .onApplicationEvent()`  and it is called only ion application start not on logback configuration change.

I was running spring boot 1.3.x, I upgraded to 1.4.0 but it's still not working.
I'm going to test with freshly grenerated gateway.

**Comment by ygokirmak** [comment]
@gmarziou  I put debug point to below line and from call trace tried to identify the fired event and handle it in logging configuration.. May it can help you also..

https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/appender/LogstashSocketAppender.java#L49

**Comment by gmarziou** [comment]
Thanks for your help but there is definitely something wrong here, I generated a gateway with JHipster 3.6.1 and I never get a ContextRefreshedEvent on logback.xml change.

I have same behavior with generated code or yours.

I have shared [a project](https://github.com/gmarziou/gateway-logstash-refresh) that shows the code and conf I use:

- devtools are not used to be sure that modifying src/main/resources/logback-spring.xml will not reload the app context
- run the app with `mvn spring-boot:run`
- while running, change logger level in src/main/resources/config/logback-spring.xml

**Comment by gmarziou** [comment]
I have created a [minimal project](https://github.com/gmarziou/gh-issues/tree/master/test-logback-reload) that shows that  ContextRefreshedEvent is not fired on logback.xml change.

**Comment by gmarziou** [comment]
I have got it working by registering a `LoggerContextListener` that adds logstash appender on reset event as shown in the log below:

<details>
<summary>
~~~
Log after changing log level in logback-spring.xml</summary>
18:57:04,904 |-INFO in ReconfigureOnChangeTask(born:1471969999958) - Detected change in configuration files.
18:57:04,904 |-INFO in ReconfigureOnChangeTask(born:1471969999958) - Will reset and reconfigure context named [default]
18:57:04,904 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_LOGSTASH] - Worker thread will flush remaining events before exiting. 
18:57:04,909 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_LOGSTASH] - Queue flush finished successfully within timeout.
18:57:04,911 |-INFO in net.logstash.logback.appender.LogstashSocketAppender[LOGSTASH] - Defaulting maxMessageSize to [8192]
18:57:04,911 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_LOGSTASH] - Attaching appender named [LOGSTASH] to AsyncAppender.
18:57:04,911 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_LOGSTASH] - Setting discardingThreshold to 102
18:57:04,911 |-INFO in com.example.LogbackLoggerContextListener@1eed657 - Added Logstash Appender
18:57:04,904 |-INFO in ReconfigureOnChangeTask(born:1471969999958) - Detected change in configuration files.
18:57:04,904 |-INFO in ReconfigureOnChangeTask(born:1471969999958) - Will reset and reconfigure context named [default]
18:57:04,904 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_LOGSTASH] - Worker thread will flush remaining events before exiting. 
18:57:04,909 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_LOGSTASH] - Queue flush finished successfully within timeout.
18:57:04,911 |-INFO in net.logstash.logback.appender.LogstashSocketAppender[LOGSTASH] - Defaulting maxMessageSize to [8192]
18:57:04,911 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_LOGSTASH] - Attaching appender named [LOGSTASH] to AsyncAppender.
18:57:04,911 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_LOGSTASH] - Setting discardingThreshold to 102
18:57:04,911 |-INFO in com.example.LogbackLoggerContextListener@1eed657 - Added Logstash Appender
18:57:04,913 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [file:/C:/projets/gh-issues/test-logback-reload/target/classes/logback-spring.xml] 
18:57:04,913 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 5 seconds
18:57:04,914 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
18:57:04,914 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
18:57:04,914 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
18:57:04,915 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.example] to INFO
18:57:04,915 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
18:57:04,915 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to Logger[ROOT]
18:57:04,915 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
18:57:04,915 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@144d9e1 - Registering current configuration as safe fallback point
~~~
</details>

I have setup a [minimal project](https://github.com/gmarziou/gh-issues/tree/master/test-logback-reload) that shows my setup.

**Comment by gmarziou** [comment]
The original issue is fixed in Spring Boot now and will be delivered as part of 1.4.1.

Regarding the issue I reported, Spring Boot team advised me to open a new issue and I haven't got feedback yet on Logback user mailing list.

**Comment by PierreBesson** [comment]
Good news ! Then I'm closing this issue as the original problem is fixed upstream and the fix will be coming soon to a future version of JHipster. As for @gmarziou's issue it is now tracked in the generator repo.
