### ISSUE TITLE
Use Curator to close old indices and improve performance

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-console#46]
Add setup for curator based on @gmarziou's idea in #44.

**Comment by ygokirmak** [comment]
@PierreBesson I can work on it.. 
is it ok to;
 - create another container which have just cron and curator
 - get cron/curator config from jhipster-curator folder ( as other modules do )
 - this container cleans old indices continuosly..

**Comment by PierreBesson** [comment]
@ygokirma that would be awesome !
I have an example here of a curator setup: https://github.com/pires/kubernetes-elasticsearch-cluster (with kubernetes).

**Comment by ygokirmak** [comment]
Ok.. I should first learn kubernetes.. will send PR when finished

**Comment by PierreBesson** [comment]
You don't need to learn Kubernetes if you don't use it 😄 , il quite complex really...
I just noticed that they used this project: https://github.com/bobrik/docker-curator with a good default config.

**Comment by PierreBesson** [comment]
This is done by @anjia0532, however we still need to add curator for the `zipkin-*` index.

**Comment by anjia0532** [comment]
ping @PierreBesson  this is my repo 
- github project https://github.com/anjia0532/docker-curator
- the docker hub https://hub.docker.com/r/anjia0532/docker-curator/ 

docker tags

lastest == curator lastest version

v5.1.2 == curator 5.1.2

the image size  only 34mb

**Comment by PierreBesson** [comment]
@anjia0532 Is your personal docker-curator project any different than what you contributed to this repo ?

**Comment by anjia0532** [comment]
@PierreBesson added [README.md](https://github.com/anjia0532/docker-curator/blob/master/README.md) to introduce how to use. nothing diff.
