### ISSUE TITLE
Add link to the Zipkin UI in Kibana using Field Formatters

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-console#51]
https://www.elastic.co/blog/kibana-4-1-field-formatters

**Comment by ygokirmak** [comment]
@PierreBesson you mean just formatting the url and make it clickable?

Seems we should add some config to https://github.com/jhipster/jhipster-console/blob/master/jhipster-console/dashboards/index-pattern/logstash.json , right?

**Comment by PierreBesson** [comment]
My idea was to add links from Kibana to Zipkin so that when reading logs in Kibana log-dashboard, you can click on the TraceID and open Zipkin to see the request trace for this traceId.

**Comment by PierreBesson** [comment]
Field formatters are so cool, I just tried adding a URL link on a TraceID fields to see the trace from which a log comes from.

**Comment by PierreBesson** [comment]
Done in v3.
