### ISSUE TITLE
jhipster-elasticsearch  Ulimit.soft must be an integer

### ISSUE THREAD

**Issue by loverto** [jhipster/jhipster-console#52]
OS:Window 10 
ERROR: for jhipster-elasticsearch  Ulimit.soft must be an integer
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 117, in perform_command
  File "compose\cli\main.py", line 922, in up
  File "compose\project.py", line 416, in up
  File "compose\parallel.py", line 69, in parallel_execute
ValueError: Ulimit.soft must be an integer
Failed to execute script docker-compose

**Comment by PierreBesson** [comment]
I know there is a problem with this for some configurations. Can you give me some information about your environment (os, docker version,...) ?

**Comment by loverto** [comment]
docker version : Docker version 17.04.0-ce-rc2, build 2f35d73
os: window 10   10.0.14393
jhipster-console : latest

**Comment by loverto** [comment]
version: '2'
services:
    jhipster-elasticsearch:
        image: jhipster/jhipster-elasticsearch
        ports:
            - 9200:9200
            - 9300:9300
        ulimits:
            memlock:
                soft: 687194767
                hard: 687194767

**Comment by PierreBesson** [comment]
Does it work if you remove the ulimit part completely ?

**Comment by loverto** [comment]
After I have modified its value, it can run;Can be the value is greater than the maximum value of Integer

**Comment by PierreBesson** [comment]
@loverto I think this issue comes from the difference between docker4windows and linux/mac.

**Comment by loverto** [comment]
May be

**Comment by PierreBesson** [comment]
fixed by 7f85bd1
