### ISSUE TITLE
jhipster-console i18n

### ISSUE THREAD

**Issue by loverto** [jhipster/jhipster-console#53]
jhipster-console i18n support

**Comment by PierreBesson** [comment]
What i18n would you want ? The console is just a packaging of the ELK stack. Did you mean to post this on the JHipster Registry repo ?

**Comment by loverto** [comment]
dashboards's title word

**Comment by PierreBesson** [comment]
As much as I love internationalisation and understand that some users need translation (I actually worked in China for 3 month). This is really not feasible from my point of view. Feel free to fork the project and translate it in your language.
