### ISSUE TITLE
Upgrading ELK stack to 5.3 and use official images

### ISSUE THREAD

**Issue by ygokirmak** [jhipster/jhipster-console#54]
I couldn't manage to configure elasticsearch to run clustered on my prod environment. I am passing these env vars to elastic container, may be they are wrong..

```
        environment:
          - cluster.name=es-cluster
          - transport.host=0.0.0.0
          - discovery.zen.minimum_master_nodes=1
```

I tried new **supported** images `docker.elastic.co/elasticsearch/elasticsearch:5.3.0` and clustering **is working** with a couple of environment variable in docker-compose
```
        environment:
          - cluster.name=es-cluster
          - "discovery.zen.ping.unicast.hosts=dh-elk-02"
```

Trying to understand the problem in images which we are using in jhipster. Should I focus to solve the problem in `elasticsearch:5.1.2-alpine` image (deprecated) or we should upgrade images to supported ones. 

I can try to upgrade and get issue #49 also which is related..

**Comment by PierreBesson** [comment]
Wow very nice. If you can PR a working clustering setup, it would be awesome. Yes you can upgrade the version.

**Comment by ygokirmak** [comment]
Ok.. I am working on that

**Comment by ygokirmak** [comment]
@PierreBesson instead of installing curl on Kibana image we can use another short-lived image to install dashboards etc? 

they did smilar here; https://github.com/elastic/stack-docker/blob/master/docker-compose.yml#L75

Putting installing dashboard and index logic into dockerfile has some drawback, warn me if I am mistaken. When we put load configuration logic in kibana dockerfile than we need to rebuild kibana image whenever we remove/clean elasticsearch image .

**Comment by PierreBesson** [comment]
@ygokirmak This is a really good idea ! The reason I didn't do it was that I was a docker noob at the time. This is definitely the way to go. This totally fits the docker philosophy of "one container for one thing" and sidekick containers.

**Comment by PierreBesson** [comment]
Love your link by the way, we should move to something like this.

**Comment by rifatdover** [comment]
+1
