### ISSUE TITLE
How about security my jhipster-console?

### ISSUE THREAD

**Issue by yattin** [jhipster/jhipster-console#57]
Now the jhipster-console can login without password.

**Comment by jdubois** [comment]
This ELK, which isn't secured by default. You shouldn't have this available publicly, which is our default setup with Docker Swarm, etc...

**Comment by PierreBesson** [comment]
This is outside of the scope of the console for now but you could achieve this in a number of ways including fronting Kibana with a basic auth / ldap secured reverse proxy. If you find a good solution you are welcome to suggest a tip to our documentation.
