### ISSUE TITLE
Add elasticsearch readiness check in import-dashboard container

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-console#67]
https://docs.docker.com/compose/startup-order/

**Comment by ygokirmak** [comment]
I had some comments about that https://github.com/jhipster/jhipster-console/pull/56

**Comment by PierreBesson** [comment]
@ygokirmak If you can do the PR with the readiness check please go on !
Initially I had some concerns about this and wanted to use the docker compose service health check but now I realize that it's not the right way to do it with pure docker. I was just too used to the k8s way which give us too many features...

**Comment by PierreBesson** [comment]
done
