### ISSUE TITLE
ZipKin Dependency Issue

### ISSUE THREAD

**Issue by somejavadev** [jhipster/jhipster-console#68]
Hi,

I tried to clone the project and run the `docker-compose up -d` command but I am receiving the following error:

> fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)

> ERROR: unsatisfiable constraints:
  coreutils (missing):
    required by: world[coreutils]

> ERROR: Service 'jhipster-zipkin' failed to build: The command '/bin/sh -c apk add --no-cache coreutils &&     curl -SL $ZIPKIN_REPO/io/zipkin/dependencies/zipkin-dependencies/$ZIPKIN_DEPENDENCIES_VERSION/zipkin-dependencies-$ZIPKIN_DEPENDENCIES_VERSION.jar > zipkin-dependencies.jar' returned a non-zero code: 1

I can confirm I am able to download the gz files. Is there perhaps anything I am missing? It might be related to https://github.com/gliderlabs/docker-alpine/issues/55 perhaps.

Regards

**Comment by PierreBesson** [comment]
This looks like a problem with alpine CDN. It happens very often. Try later or configure an alternative cdn, please look into alpine docs...

**Comment by jdubois** [comment]
yes, the error message says it's an error in the CDN
