### ISSUE TITLE
jhipster-import-dashboards's wait-for-elasticsearch.sh: Permission denied

### ISSUE THREAD

**Issue by anjia0532** [jhipster/jhipster-console#70]
git clone the latest jhipster-console and  build it from `docker build jhipster-import-dashboards -t jhipster-import-dashboards` ,but this container it's not work.

```bash
2017/8/4 下午2:27:41/bin/sh: ./wait-for-elasticsearch.sh: Permission denied
2017/8/4 下午2:27:57/bin/sh: ./wait-for-elasticsearch.sh: Permission denied
```

the `create-index-patterns.sh` and `wait-for-elasticsearch.sh` ownner is root.

```bash
bash-4.2$ ls -lah
total 13M
drwxr-x--- 1 root metricbeat 4.0K Aug  3 14:07 .
drwxr-x--- 1 root metricbeat 4.0K Aug  3 14:07 ..
-rw-rw-r-- 1 root root        333 Aug  3 09:40 create-index-patterns.sh
-rwxr-x--- 1 root metricbeat  13M Jul 18 20:40 import_dashboards
-rwxr-x--- 1 root metricbeat  15K Jul 18 20:39 migrate_beat_config_1_x_to_5_0.py
-rw-rw-r-- 1 root root        242 Aug  3 09:40 wait-for-elasticsearch.sh
bash-4.2$
```

**Comment by PierreBesson** [comment]
Strange because it works on the docker hub. Can you chown the files and PR the change ?

**Comment by anjia0532** [comment]
the jhipster/jhipster-import-dashboards it's ok, and the  `create-index-patterns.sh` and `wait-for-elasticsearch.sh` ownner is root too. i dont know what's happend.

btw , why use the metricbeat image? this module create-index and import_dashboards and shutdown.

only for  ./import_dashboards ?

**Comment by anjia0532** [comment]
@PierreBesson it's my fault. the *.sh without executable permissions.
should be this
```bash
sudo chmod +x *.sh
sudo docker build jhipster-import-dashboards -t jhipster-import-dashboards
```

**Comment by PierreBesson** [comment]
Yes we use it only for the import-dashboard script.
