### ISSUE TITLE
Update the official documentation regarding Elastalert

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/jhipster-console#75]
According to the official Jhipster website, there is a Kibana dashboard to display Elastalert alerrs
https://jhipster.github.io/monitoring/#elastalert
> Go to http://localhost:5601/app/kibana#/dashboard/alerting-dashboard to see the history of all your alerts.

I tried but there is no dashboard anymore, confirmed by the following commit:
https://github.com/jhipster/jhipster-console/commit/33d54082f396a151b9e3ba984f221f833f66a1a3

I tried to install the plugin by my self using  [BitSensor documentation](https://bitsensor.io/blog/elastalert-kibana-plugin-centralized-logging-with-integrated-alerting) but failed also. I think BitSensor developped this dashboard for internal use mainly not for OSS.

I think The official doc should present Elastalert rules but no the rest is misleading.

**Comment by PierreBesson** [comment]
Yes I removed the Elastalert dashboard following reports that it does not work.
I did have a look to bitsensor's project but then realized that it is not useful at all and just a tiny part of their proprietary product.

Currently I'm not using Elastalert myself (for company reasons...) so there is not much I can do to improve support but some users have had success using it like @anjia0532 who contributed to update the solution and even wrote a reporter for wechat https://github.com/anjia0532/elastalert-wechat-plugin (:warning: in chinese :smiley:).

I will work on the docs to remove outdated info.

**Comment by anjia0532** [comment]
sorry, my english is not very good , but i am working on it.([elastalert-wechat-plugin](https://github.com/anjia0532/elastalert-wechat-plugin) is wechat plugin for elastalert,wechat is a very popular im app in china, to save the expense i create this plugin  : D   )

In the open source world, If you think you can do better, you shouldn't waiting for someone else's work, you can and you will perfect it to help more people.  it looks cool, right?

China has a proverb :` If you can do it then you should go up and do it`

**Comment by danielpetisme** [comment]
@PierreBesson if you're not using elastalert, can you share your alarming solution (if not confidential)?

Regarding the issue, I have my answer so feel free to close it or keep it open as reminder.
Thank you all

**Comment by PierreBesson** [comment]
Currently we are not using any alerting solution but I quite like Elastalert as it is very powerful although it takes some time to setup and there is no UI. I've also heard that there is a new alerting integration in the paid version of Kibana.

Also I want to try out this third party plugin :
https://github.com/sirensolutions/sentinl

**Comment by PierreBesson** [comment]
docs updated at : https://github.com/jhipster/jhipster.github.io/pull/470

**Comment by danielpetisme** [comment]
I've tested sentinl 
Docker image: https://hub.docker.com/r/danielpetisme/jhipster-console-sentinl/
Souce: https://github.com/danielpetisme/jhipster-console-sentinl

My feedback:
It's clearly a ~beta~ alpha:
- Rely on the Elasticsearch query dsl to fine event so very flexible but more touchy than Elastalert
- UI is messy (2 buttons save and the actual save is random)
- Doc absent (4-5 working examples but not definition of the structure to use)
- The script capabilities is a good idea but not documented
- The mustache templating is a great idea

Not ready at all to be used as production solution.

I also tried to install the Elastalert Kibana plugin by tweaking the sources (fixing the kibana version in the `package.json`) but still don't work.
I found that the plugin is still in a active dev stage and the sources are hosted here (github is a mirror):
https://git.bitsensor.io/front-end/elastalert-kibana-plugin

I guess I'll stick with the classic `jhipster-alerter` + yaml rules without UI.

**Comment by PierreBesson** [comment]
@danielpetisme Thanks a lot you are saving me some time. Too bad that there is no good UI for alerts yet.
Maybe this will be the solution: https://github.com/grafana/grafana/pull/8934
