### ISSUE TITLE
run without docker

### ISSUE THREAD

**Issue by cenggel** [jhipster/jhipster-console#77]
who to use jhipster-console without docker environment ?

**Comment by PierreBesson** [comment]
This is possible but it's a manual process. The Console is basically the vanilla ELK stack with some dashboards. Have a look to the ELK docs from Elastic then use our ES, logstash and Kibana config and import our dashboards by pointing the import-dashboard container to your Elasticsearch instance.
Good luck.

I would gladly welcome a PR to our website if you have the detailed steps written down.
