### ISSUE TITLE
How to run jhipster-console in windows without docker?

### ISSUE THREAD

**Issue by GuruvaiahG** [jhipster/jhipster-console#79]
Hi ,

i want run jhipster-console windows without using docker as we run registry or gateway .please suggest me how to proceed.

**Comment by pascalgrimaud** [comment]
Hi,

You simply can't, as JHipster console is developed for beeing used with Docker. 

But you can read the code here, then, manually install the full stack: elasticsearch, logstash and kibana

**Comment by GuruvaiahG** [comment]
can you please specify where is the code for read?
