### ISSUE TITLE
Error in docker-compose up

### ISSUE THREAD

**Issue by Marcuccio** [jhipster/jhipster-console#85]
I needed modify the `logtrail.json` for a custom configuration. I used `docker-compose up` on `bootstrap/docker-compose.yml` unsuccesfull due the remote pulling of the images.

I modified the `bootstrap/docker-compose.yml` to use the local dockerfile:
```yaml
   jhipster-console:
        build: ../jhipster-console
```
but this threw an error:

> Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [logtrail]. Expected [6.1.0]; found [6.1.1]"

Was this an expected result?
Is it possible modify the logtrail.json configuration?

**Comment by PierreBesson** [comment]
Oh yes I had fixed it locally but did forget to push. It should be fixed now on master and a release is coming quickly.
