### ISSUE TITLE
Release workflow

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-console#87]
@PierreBesson : as you are admin on this repo, what do you think about working together on the automated release workflow ?
The goal would be to simply merge into a `release` branch
Then, Travis will build, then tag (need to config Travis to add some Environment Variables) and all the release process will trigger automatically.

**Comment by PierreBesson** [comment]
Well the console release is already automated on docker hub. I just have to tag the repo to trigger a release.

**Comment by pascalgrimaud** [comment]
Indeed, so nothing to do here
