### ISSUE TITLE
Zpkin error

### ISSUE THREAD

**Issue by Marcuccio** [jhipster/jhipster-console#88]
At http://localhost:9411 in the `Zipkin` homepage this error banner is shown:

![image](https://user-images.githubusercontent.com/9968234/34678206-b02a4718-f492-11e7-8e06-94a005087368.png)

**Comment by PierreBesson** [comment]
Please specify which version of the console you are using. I know it works with the latest v3.0.1 but you need to use the same version for all docker image. This is criticaly important in recent version of the Elastic stack.

**Comment by PierreBesson** [comment]
Please specify which version of the console you are using. I know it works with the latest v3.0.1 but you need to use the same version for all docker image. This is criticaly important in recent versions of the Elastic stack.

**Comment by PierreBesson** [comment]
Please specify which version of the console you are using. I know it works with the latest v3.0.1 but you need to use the same version for all docker image. This is criticaly important in recent versions of the Elastic stack.

**Comment by PierreBesson** [comment]
Please specify which version of the console you are using. I know it works with the latest v3.0.1 but you need to use the same version for all docker image. This is criticaly important in recent versions of the Elastic stack.

**Comment by Marcuccio** [comment]
I'm using the latest release: _v3.0.1_ and starting everything with `bootstrap/the docker-compose.yml ` file.

I tried again this morning but still this error shows up.

**Comment by PierreBesson** [comment]
Oh yeah the version was specified in this docker-compose file so you might have conflicting versions. I have added the `latest` tag in this commit : https://github.com/jhipster/jhipster-console/commit/9aed8ce9a7da7656b76ac1148cdbfb901e3bd977
Try running `docker-compose pull && docker-compose up -d` again.
