### ISSUE TITLE
ERROR: for jhipster-alerter  Cannot start service jhipster-alerter: OCI runtime create failed: 

### ISSUE THREAD

**Issue by ghost** [jhipster/jhipster-console#89]
I get error on jhipster-alerter when installing accroding to http://www.jhipster.tech/monitoring/
Directory /Users/jonas/source/intellij/company/xxx/app/alerts/config.yaml exists. Using a mac.

Digest: sha256:9fe2c24d7bcfb58484c5ba53a0791618010d8cf941fc4818c6b4f21fd09b1f0b
Status: Downloaded newer image for jhipster/jhipster-import-dashboards:latest
Creating movementservice_jhipster-zipkin_1            ... done
Creating movementservice_jhipster-alerter_1           ... error
Creating movementservice_jhipster-alerter_1           ...
Creating movementservice_jhipster-console_1           ... done
Creating movementservice_jhipster-elasticsearch_1     ... done
Creating movementservice_jhipster-console_1           ...

Creating movementservice_jhipster-logstash_1          ... done
used \"rootfs_linux.go:58: mounting \\\"/Users/jonas/source/intellij/company/xxx/app/alerts/config.yaml\\\" to rootfs \\\"/var/lib/docker/overlay2/74e34bac2e971ec74bd5b70f6eb6fa74279d6ad8b4e645b583e4d0ebc0Creating movementservice_jhipster-curator_1           ... done
 to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Creating movementservice_jhipster-import-dashboards_1 ... done

ERROR: for jhipster-alerter  Cannot start service jhipster-alerter: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"rootfs_linux.go:58: mounting \\\"/Users/jonas/source/intellij/company/xxx/app/alerts/config.yaml\\\" to rootfs \\\"/var/lib/docker/overlay2/74e34bac2e971ec74bd5b70f6eb6fa74279d6ad8b4e645b583e4d0ebc0522402/merged\\\" at \\\"/var/lib/docker/overlay2/74e34bac2e971ec74bd5b70f6eb6fa74279d6ad8b4e645b583e4d0ebc0522402/merged/opt/elastalert/config.yaml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

**Comment by sghino** [comment]
I get the same error using linux.

**Comment by zhx828** [comment]
Same here from Mac

**Comment by kaidohallik** [comment]
Same error on Windows 10

**Comment by Marcuccio** [comment]
Still no updates?

**Comment by PierreBesson** [comment]
Hi guys,

Sorry for taking a long time tout answer this
Please consider the jhipster-alerter broken with the latest version for now, so comment out the alerter section in the docker-compose file. This is due to incompatible Elasticsearch versions and my focus not being on alerting right now.

I hope to have the time to resume work on alerting some time next month. In the meantime I'm always welcome for outside contributions.

**Comment by orovp** [comment]
Still no updates?

**Comment by pathfinder2104** [comment]
Any updates on this?? Can I downgrade Alerter version? How?

**Comment by pascalgrimaud** [comment]
it will be fixed when someone is motivated and have time to do it.
So contributions are really welcome.

**Comment by pathfinder2104** [comment]
cool, I will give it a shot.

**Comment by lmbai** [comment]
It should be fix now with the new elastalert 0.1.33, which is compatible with the ES6. (https://github.com/jhipster/jhipster-console/pull/98#issuecomment-411671766)Waiting Jhipster side to build the new image .

**Comment by PierreBesson** [comment]
Yes this is now fixed, expect a release soon.

**Comment by singhnirmal90** [comment]
@PierreBesson Could you please notify if its fixed? Any new instructions to get it working (its still commented out in docker-compose)?

**Comment by poolebu** [comment]
I think it's a windows issue, see https://github.com/jhipster/jhipster-console/issues/105#issuecomment-475857498
