### ISSUE TITLE
Logtrail 6.1.3 Linking Issue

### ISSUE THREAD

**Issue by jsendlewski** [jhipster/jhipster-console#92]
Hi!

I'd suggest bumping version of Logtrail, since 6.1.3-0.1.25 has the [following](https://github.com/sivasamyk/logtrail/issues/238) bug. It was fixed in 6.2.1-0.1.26.

Thanks for the hard work!

**Comment by PierreBesson** [comment]
Fixed as logtrail is updated in master.
